name: Project Suggestion
description: Suggest a project for the community to work on
title: "Project Suggestion: {{ body.title }}"
labels: ["project", "triage"]
assignees:
  - trtmn
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: title
    attributes:
      label: Title
      description: A short description of the code project
      placeholder: Enter a title
      value: ""
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Tell us a bit more (full instructions here)
      placeholder: Tell us what to do!
      value: "Go build this thing that does this..."
    validations:
      required: true
